name: Vindicator
version: ${project.version}
description: A user management plugin
author: jgeboski
main: org.jgeboski.vindicator.Vindicator
softdepend: [CraftIRC]

commands:
  ban:
    description: Ban a player or IP from the server
    aliases: [banip, tban, tempban, tmpban]
    usage: /<command> <player/IP> [time] [reason]
  kick:
    description: Kick a player or IP from the server
    aliases: []
    usage: /<command> <player/IP> [reason]
  lookup:
    description: Lookup a player or IP
    aliases: []
    usage: /<command> <player/IP>
  mute:
    description: Mute a player
    aliases: []
    usage: /<command> <player> [time] [reason]
  noteadd:
    description: Add a player or IP note
    aliases: [addnote, newnote]
    usage: /<command> <player/IP> <note>
  noterem:
    description: Remove a player or IP note
    aliases: [delnote, notedel, remnote]
    usage: /<command> <player/IP> <index>
  unban:
    description: Unban a player or IP from the server
    aliases: [pardon, unbanip]
    usage: /<command> <player/IP>
  unmute:
    description: Unmute a player
    aliases: []
    usage: /<command> <player>
  vindicator:
    description: Vindicator management
    aliases: [vind]
    usage: /<command> reload

permissions:
  vindicator.ban:
    description: Ban a player or IP from the server
    default: op
    children:
      vindicator.message.ban: true
  vindicator.kick:
    description: Kick a player or IP from the server
    default: op
    children:
      vindicator.message.kick: true
  vindicator.lookup:
    description: Lookup a player or IP
    default: op
  vindicator.manage:
    description: Access to the vindicator command
    default: op
  vindicator.manage.reload:
    description: Reload Vindicator
    default: op
    children:
      vindicator.manage: true
  vindicator.mute:
    description: Mute a player
    default: op
    children:
      vindicator.message.mute: true
  vindicator.noteadd:
    description: Add a player or IP note
    default: op
    children:
      vindicator.message.noteadd: true
  vindicator.noterem:
    description: Remove a player or IP note
    default: op
    children:
      vindicator.message.noterem: true
  vindicator.unban:
    description: Unban a player or IP from the server
    default: op
    children:
      vindicator.message.unban: true
  vindicator.unmute:
    description: Unmute a player
    default: op
    children:
      vindicator.message.unmute: true

  vindicator.message.ban:
    description: Receive a message upon a ban
    default: op
  vindicator.message.kick:
    description: Receive a message upon a kick
    default: op
  vindicator.message.mute:
    description: Receive a message upon a mute
    default: op
  vindicator.message.noteadd:
    description: Receive a message upon a note addition
    default: op
  vindicator.message.noterem:
    description: Receive a message upon a note removal
    default: op
  vindicator.message.notify:
    description: Receive a message if there are notes/bans
    default: op
  vindicator.message.unban:
    description: Receive a message upon an unban
    default: op
  vindicator.message.unmute:
    description: Receive a message upon an unmute
    default: op
